# Generated by Django 4.2.5 on 2024-02-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='pressure',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
