# Generated by Django 4.2.5 on 2024-02-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_weather_humidity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='coordinate',
            field=models.CharField(max_length=10),
        ),
    ]
