# Generated by Django 4.2.5 on 2024-02-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_weather_coordinate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='temp',
            field=models.CharField(max_length=10),
        ),
    ]
