# Generated by Django 4.2.5 on 2024-02-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_weather_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='humidity',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='weather',
            name='pressure',
            field=models.CharField(max_length=10),
        ),
    ]
